spring:
  application:
    name : baseshelf
  datasource:
    url: jdbc:postgresql://localhost:5436/baseshelfdb1
    username: baseshelf
    password: 2024baseshelf@
    driver-class-name: org.postgresql.Driver
  jpa:
#    properties:
#      hibernate:
#        generate_statistics: true
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    show-sql: true

#logging:
#  level:
#    root: INFO
#    org:
#      hibernate:
#        stat: DEBUG
#        SQL: DEBUG
